### ISSUE TITLE
Can't get Touhou Puppet Dance Performance to run on Locate

### ISSUE THREAD

**Issue by VermillionZero** [xupefei/Locale-Emulator#115]
I'm having some trouble trying to get TPDP (FocusLens) to run with Locate Emulator 2.0.1.0. When I tried to run the Setup.exe with Locate, this error message appears:

LEProc.exe - Entry Point Not Found

The procedure entry point RtlKnownExceptionFilter could not be located in the dynamic link library ntdll.dll.

Then it goes on saying something like this in another window that pops up:

System.IO.FileNotFoundException: C:\Windows\System32\KERNELBASE.DLL
at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
at LECommonLibrary.GlobalHelper.GenerateSystemDIIVersionList()
at LECommonLibrary.GlobalHelper.ShowErrorDebugMessageBox(String
commandLine, UInt32 errorCode)
at LEProc.Program.DoRunWithLEProfile(String path, LEProfile profile)

I need to run Locale Emulator to run on both the Setup.exe and the Game.exe, because without it everything is displayed in odd symbols and moonrunes, making the game too confusing to play. I currently am using Windows Vista 32.Bit.

**Comment by xupefei** [comment]
Sorry, Locale Emulator requires at least Windows 7 to run.

**Comment by VermillionZero** [comment]
Ah... I suspected as much... You have my sincerest thanks, xupefei.
